### ISSUE TITLE
Use of the line drawing algorithm

### ISSUE THREAD

**Issue by ajstarks** [wrnrlr/shape#1]
Note that I've adapted your line drawing algorithm to use the latest version of Gio, in giocanvas: https://github.com/ajstarks/giocanvas  

A test program is here: https://github.com/ajstarks/giocanvas/blob/master/lines/main.go

Output:
![Screenshot from 2020-06-08 11-25-21](https://user-images.githubusercontent.com/169692/84051300-ee767180-a97c-11ea-8f12-561e4225355e.png)

**Comment by wrnrlr** [comment]
Great job on the canvas library, I love the artwork. My work on the shape library got stuck when I tried to generalise the problem to polylines with support for offsetting brezier curves.  From what I could find in the literature most solutions use different strategies from what I was doing, I've put some link for more info in my code, maybe that you can figure it out :)

// An algorithm for polylines outline construction
// http://old.cescg.org/CESCG99/SKrivograd/
//
// https://www.codeproject.com/Articles/226569/Drawing-polylines-by-tessellation
//
// A Realistic 2D Drawing System
// https://keithp.com/~keithp/talks/cairo2003.pdf
//
// https://stackoverflow.com/questions/5641769/how-to-draw-an-outline-around-any-line
//
// Drawing Lines is Hard
// https://mattdesl.svbtle.com/drawing-lines-is-hard

**Comment by ajstarks** [comment]
thanks! I note some dead code in bezel -- can the if statements be removed? what is the purpose of this function?

**Comment by wrnrlr** [comment]
For normal lines it can be removed. What that code was meant to do was join two lines of a polyline. There is a bug in my implementation where the "top" and "bottom" line would cross because the top and bottom point of the bezel where flipped for certain line angle. It is one of those things I didn't figure out.
